
title: nvs.schreib.at
email: juri@schreib.at
description: >
  Simple Management Tool for Writing Doucmentions in Markdown
baseurl: ""
url: "http://nvs.schreib.at"
twitter_username: bujuhu
github_username:  bujuhu

# Build settings
markdown: kramdown

#Protcol Variables
name: Juri Schreib
class: 5CHIF
reportTitle: Laborbericht

exclude:
  - node_modules
  - CNAME
  - LICENSE
  - nvs
collections:
  nvs:
    short: NVS
    long: NVS Coufal 5CHIF 16/17
    output: true
    permalink: /NVS/:name
  dbi_r:
    short: DBI
    long: DBI Resch 5CHIF 16/17
    output: true
    permalink: /DBI_R/:name
  dbi_gt:
    short: DBI
    long: DBI Griesmayer 5CHIF 16/17
    output: true
    permalink: /DBI_GT/:name

subjects:
  - nvs
  - dbi
  - dbi resch
