
title: nvs.schreib.at
email: juri@schreib.at
description: >
  Simple Management Tool for Writing Doucmentions in Markdown
baseurl: ""
url: "http://nvs.schreib.at"
twitter_username: bujuhu
github_username:  bujuhu

# Build settings
markdown: kramdown

exclude:
  - node_modules
  - CNAME
  - LICENSE
  - nvs
collections:
  nvs:
    short: NVS
    long: NVS Coufal 5CHIF 16/17
    output: true
  dbi_r:
    short: DBI
    long: DBI Resch 5CHIF 16/17
    output: true
  dbi_gt:
    short: DBI
    long: DBI Griesmayer 5CHIF 16/17
    output: true
  contributions:
    short: Beiträge
    long: Beiträge
    output: true

defaults:
  - scope:
      path: ""
      type: nvs
    values:
      layout: report
      author: Juri Schreib
      class: 5CHIF 16/17
  - scope:
      path: ""
      type: dbi_r
    values:
      layout: report
      author: Juri Schreib
      class: 5CHIF 16/17
  - scope:
      path: ""
      type: dbi_gt
    values:
      layout: report
      author: Juri Schreib
      class: 5CHIF 16/17
  - scope:
      path: ""
      type: contributions
    values:
      layout: report
      author: Anonym
      class: Anonym
